server:
  port: 8001



mybatis-plus:
  typeAliasesPackage: com.follow.entity.* #实体类路径
  mapper-locations: classpath:com/follow/mapper/xml/*.xml
  global-config:
    db-config:
      id-type: id_worker #保存时如果主键为空，mybatis自动为我们插入主键，类型为雪花算法
    worker-id: 1 #机器编码
    datacenter-id: 1 #机房编码 用于分布式下生成唯一ID
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql,生产环境需关闭


spring:
  application:
    name: microsespringcloud-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/follow?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://www.cht7001.cn:7001/eureka/,http://www.cht7002.cn:7002/eureka/,http://www.cht7003.cn:7003/eureka/
  instance:
    instance-id: icrosespringcloud-user-8001
    prefer-ip-address: true

info:
  app.name: follow-user-provider
  company.name: www.cht.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$