server:
  port: 3344

spring:
  application:
    name: follow-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/422078082/follow-config.git
          username: 422078082@qq.com
          password: gxcht123456
encrypt:
  key: foo
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false