server:
  port: 80
  #context-path: /
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://www.cht7001.cn:7001/eureka/,http://www.cht7002.cn:7002/eureka/,http://www.cht7003.cn:7003/eureka/

