server:
  port: 80
  context-path: /

spring:
  application:
    name: MICROSESPRINGCLOUD-USER_COMSUMER

eureka:
  client:
    service-url:
      defaultZone: http://www.cht7001.cn:7001/eureka/,http://www.cht7002.cn:7002/eureka/,http://www.cht7003.cn:7003/eureka/
    instance:
      prefer-ip-address:  true #显示IP的地址
    register-with-eureka: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true
  eager-load:
    enabled: true
feign:
  hystrix:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  prefix: /api
  ignored-services: "*"
  routes:
    user-service:
        path: /user-service/**
        serviceId: microsespringcloud-user

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000




