server:
  port: 80


spring:
  application:
    name: MICROSESPRINGCLOUD-USER_COMSUMER
  redis:
    host: test.zykjct.com
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-idle: 10
        max-active: 8
        min-idle: 5

eureka:
  client:
    service-url:
      defaultZone: http://www.cht7001.cn:7001/eureka/
  instance:
      prefer-ip-address:  true #显示IP的地址




ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true
  eager-load:
    enabled: true
feign:
  hystrix:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  prefix: /api
  ignored-services: "*"
  routes:
    user-service:
      path: /user-service/**
      serviceId: microsespringcloud-user

TOKEN:
  AGINGTIME: 12000 #单位为分




