server:
  port: 7001

eureka:
  instance:
    hostname: www.cht7001.cn #eureka服务端的名称
  client:
    register-with-eureka: false #自己不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
       defaultZone: http://www.cht7002.cn:7002/eureka/,http://www.cht7003.cn:7003/eureka/